IF 
	%BGT_VAR%
	CombatCounter(0) !See([ENEMY]) 
	OR(2) InParty("C#Brandock") Global("C#BrandockJoined","GLOBAL",2)
	OR(2) InParty("C#Grey") Global("C#GreyJoined","GLOBAL",2)
	See("C#Grey") See(Player1)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	Global("C#Brandock_GreyBG1","GLOBAL",3)
	RealGlobalTimerExpired("C#BrandockNPCBanterTimer","GLOBAL")
THEN
RESPONSE #100
	SetGlobal("C#Brandock_GreyBG1","GLOBAL",4)
	StartDialogNoSet(Player1)
END