
IF
	Global("BD_AREA_HOSTILE","BD5300",1)
	!GlobalTimerNotExpired("bd_sdd350b_ot_timer","bd2000")
	Global("C#GreySoD_bd_ot","bd5300",0)
	IsValidForPartyDialogue("C#Grey")  
	TriggerOverride("C#Grey",Range([ENEMY.0.0.0.HOSTILES3],30))
THEN
	RESPONSE #100
		SetGlobalTimer("bd_sdd350b_ot_timer","bd2000",THREE_MINUTES)
		SetGlobal("C#GreySoD_bd_ot","bd5300",1)
		DisplayStringHead("C#Grey",@50010)  
END