
IF
	Global("C#Grey_GreyJondalar","GLOBAL",1)
	Detect(Player1)
	Range(Player1,18)
	Range("C#GrErik",15)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	!See([ENEMY])
	CombatCounter(0)
THEN
  RESPONSE #100
	StartDialogNoSet(Player1)
END

IF
	GlobalLT("C#Grey_GreyJondalar","GLOBAL",2)
	OR(2) InParty("C#Grey") Global("C#GreyJoined","GLOBAL",2)
	!Range(Player1,15)
THEN
  RESPONSE #100
	MoveToObject(Player1)
END




